version: '3'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service:ubuntu
    build: .
    volumes:
      - ./log/text.log:/usr/src/app/text.log
    container_name: simple-web
