version: "3.8"

services: # In default netwokr, containers are reachable and discoverable
  front:
    build:
      context: $PWD/../../material-applications/example-frontend
      dockerfile: $PWD/Dockerfiles/Dockerfile.frontend
    ports:
      - 5000:5000
    container_name: frontend

  back:
    build:
      context: $PWD/../../material-applications/example-backend
      dockerfile: $PWD/Dockerfiles/Dockerfile.backend
    environment:
      - REDIS_HOST=redis # same as hostname, not the container_name
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
    ports:
      - 8080:8080
    container_name: backend

  redis: # hostname = container_name
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    container_name: redisdb

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=user
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: postgresdb
