FROM node:14

WORKDIR /usr/src/app

EXPOSE 5000

COPY . .

RUN npm install && \
    REACT_APP_BACKEND_URL=http://localhost/api npm run build && \
    npm install -g serve && \
    useradd -m appuser

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
