version: '3'

services:
  front:
    build:
      context: ./../../material-applications/example-frontend
      dockerfile: Dockerfile.frontend 
    ports:
      - 5000:5000
    container_name: frontend

  back:
    build:
      context: ./../../material-applications/example-backend
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    container_name: backend
