version: '3'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service:ubuntu
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./log/text.log:/usr/src/app/text.log
    command: ["./usr/src/app/server","server"]
    container_name: simple-web
