FROM node:14

WORKDIR /usr/src/app

EXPOSE 5000

COPY . .

RUN npm install

RUN REACT_APP_BACKEND_URL=http://localhost/api npm run build

RUN npm install -g serve

RUN useradd -m appuser

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
