version: '3.8'

services:
  front:
    container_name: frontend
    build:
      context: $PWD/ml-kurkkumopo-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  
  back:
    container_name: backend
    build:
      context: $PWD/ml-kurkkumopo-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - train
      - front
  
  train:
    container_name: training
    build:
      context: $PWD/ml-kurkkumopo-training
      dockerfile: Dockerfile
    volumes:
      - model:/src/model
      - imgs:/src/imgs

volumes:
  model:
  imgs:
